default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     ""

development:
  <<: *default
  template: template0
  database: catan_development

test:
  <<: *default
  template: template0
  database: app_test

production:
  <<: *default
  template: template0
  database: app_production